print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("haha")
print("dupa")
print("dupa")
print("dupa")
print("dupa chuj kurwa cipa pizda " +
      "ja pierdole chuj lurwa fjdsklfgjasdlkgjsdfklgsfghdfsgfsd")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
print("dupa")
